version: '3.6'
services:
  postgresql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_DB=bootcamp
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: